"""added conversation tag and deleted pendind status

Revision ID: 4e9b65e1d4ca
Revises: 5d91a1433240
Create Date: 2023-06-13 19:14:21.109099

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e9b65e1d4ca'
down_revision = '5d91a1433240'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tag', sa.String(length=1000), nullable=False))
        batch_op.drop_column('is_pending')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_pending', sa.BOOLEAN(), nullable=False))
        batch_op.drop_column('tag')

    # ### end Alembic commands ###
